development:
  adapter:  mysql2
  host:     127.0.0.1
  encoding: utf8
  database: utc-blog
  pool:     5
  username: kmcfly
  password: lenovo
  template: template0

test:
  adapter:  postgresql
  host:     127.0.0.1
  encoding: utf8
  database: utc-blog
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     127.0.0.1
  encoding: utf8
  database: utc-blog
  pool:     5
  username: postgres
  password: postgres
  template: template0
